<?php

/**
 * @file
 * Textimage - Provides text to image manipulations.
 */

use Drupal\Component\Utility\Unicode;
use Drupal\textimage\Component\ColorUtility;
use Drupal\textimage\Textimage;
use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Define constants.
 */
define('TEXTIMAGE_FONTYOURFACE_MIN_VERSION', '7.x-2.6');
define('TEXTIMAGE_MEDIA_MIN_VERSION', '7.x-1.2');
define('TEXTIMAGE_JQUERY_COLORPICKER_MIN_VERSION', '7.x-1.0-rc1');
define('TEXTIMAGE_TOKEN_MIN_VERSION', '7.x-1.5');

/**
 * Hooks implementations.
 */

/**
 * Implements hook_help().
 */
function textimage_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    case 'textimage.settings':
      $output = '<p>';
      $output .= t('Textimage provides image effects to generate images with overlaid text. ');
      $output .= t('Use <a href="@image">Image styles</a> features to create Image styles. ', array('@image' => url('admin/config/media/image-styles')));  // @todo use route
      $output .= t('Adding Textimage effects to a style will identify it as relevant for Textimage. ');
      $output .= t('On the edit image style form, a "Textimage options" section allows selecting Textimage-specific options for the style.');
      $output .= '</p>';
      return $output;

  }
}

/**
 * Implements hook_theme().
 */
function textimage_theme() {
  $theme = array(
    // Format a textimage.
    'textimage_formatter' => array(
      'variables' => array(
        'textimage' => NULL,
        'style_name' => '',
        'effects' => array(),
        'text'   => array(),
        'extension' => 'png',
        'caching' => TRUE,
        'node' => NULL,
        'source_image_file' => NULL,
        'target_uri' => NULL,
        'force_hashed_filename' => FALSE,
        'alt'    => '',
        'title'  => '',
        'attributes' => array(),
        'image_container_attributes' => array(),
        'href' => '',
      ),
      'template' => 'textimage-formatter',
    ),
    // Textimage background image effect - summary.
    'textimage_background_effect_summary' => array(
      'variables' => array('data' => NULL),
      'template' => 'textimage-background-summary',
    ),
    // Textimage text image effect - summary.
    'textimage_text_summary' => array(
      'variables' => array('data' => NULL),
      'template' => 'textimage-text-summary',
    ),
    // Render a color information box and string.
    'textimage_color_detail' => array(
      'variables' => array(
        'color' => '#000000',
        'border' => FALSE,
        'border_color' => '#000000',
      ),
      'template' => 'textimage-color-detail',
    ),
  );

  return $theme;
}

/**
 * Implements hook_file_download().
 *
 * Control the access to files underneath the styles directory.
 */
function textimage_file_download($uri) {
  $path = file_uri_target($uri);

  // Private file access for image style derivatives.
  if (strpos($path, 'textimage') === 0) {
    $args = explode('/', $path);
    // Discard the first part of the path (textimage).
    array_shift($args);
    // Get the style name from the second part.
    $style_name = array_shift($args);
    // Remove the filename from the path.
    array_shift($args);

    // Then the remaining parts are the path to the image.
    $original_uri = file_uri_scheme($uri) . '://' . implode('/', $args);

    // Check that the file exists and is an image.
    $image = \Drupal::service('image.factory')->get($uri);
    if ($image->isValid()) {
      // Check the permissions of the original to grant access to this image.
      $headers = \Drupal::moduleHandler()->invokeAll('file_download', array($original_uri));
      // Confirm there's at least one module granting access and none denying access.
// @todo implement a download controller / file permissions   if (!empty($headers) && !in_array(-1, $headers)) {
      if (!in_array(-1, $headers)) {
        return array(
          // Send headers describing the image's size, and MIME-type...
          'Content-Type' => $image->getMimeType(),
          'Content-Length' => $image->getFileSize(),
          // By not explicitly setting them here, this uses normal Drupal
          // Expires, Cache-Control and ETag headers to prevent proxy or
          // browser caching of private images.
        );
      }
    }
    return -1;
  }

  // Private file access for the original files. Note that we only
  // check access for non-temporary images, since file.module will
  // grant access for all temporary files.
  $files = entity_load_multiple_by_properties('file', array('uri' => $uri));
  if (count($files)) {
    $file = reset($files);
    if ($file->status) {
      return file_file_download($uri, 'image');
    }
  }
}

/**
 * Implements hook_cache_flush().
 */
function textimage_cache_flush() {
  return array('textimage');
}

/**
 * Implements hook_cron().
 */
function textimage_cron() {
  $uncached_dir = \Drupal::service('textimage.factory')->getStorePath('uncached');
  // Remove temporary, uncached, image files.
  if (file_exists($uncached_dir)) {
    if (file_unmanaged_delete_recursive($uncached_dir)) {
      _textimage_diag(t("Textimage temporary image files removed."), WATCHDOG_NOTICE);
    }
    else {
      _textimage_diag(t("Textimage could not remove temporary image files."), WATCHDOG_ERROR, __FUNCTION__);
    }
  }
}

/**
 * Implements hook_token_info().
 */
function textimage_token_info() {
  $type = array(
    'name' => t('Textimage'),
    'description' => t('Tokens related to Textimage'),
    'needs-data' => 'node',
  );
  $tokens = array(
    'uri' => array(
      'name' => t("URI"),
      'description' => t("The URI(s) of a Textimage generated for a node's field. Use like <strong>[textimage:uri:field{:display}{:sequence}]</strong>, where:<br/><strong>field</strong> is the machine name of the field for which the Textimage is generated (e.g. body or field_xxxx);<br/><strong>display</strong> is an optional indication of the display view mode (e.g. default, full, teaser, etc.); 'default' is used if not specified; <br/><strong>sequence</strong> is an optional indication of the URI to return if Textimage produces more images for the same field (like e.g. in a multi-value Image field); if not specified, a comma-delimited string of all the URIs generated will be returned."),
      'dynamic' => TRUE,
    ),
    'url' => array(
      'name' => t("URL"),
      'description' => t("The URL(s) of a Textimage generated for a node's field. Use like <strong>[textimage:url:field{:display}{:sequence}]</strong>, where:<br/><strong>field</strong> is the machine name of the field for which the Textimage is generated (e.g. body or field_xxxx);<br/><strong>display</strong> is an optional indication of the display view mode (e.g. default, full, teaser, etc.); 'default' is used if not specified; <br/><strong>sequence</strong> is an optional indication of the URL to return if Textimage produces more images for the same field (like e.g. in a multi-value Image field); if not specified, a comma-delimited string of all the URLs generated will be returned."),
      'dynamic' => TRUE,
    ),
  );
  return array(
    'types'  => array('textimage' => $type),
    'tokens' => array('textimage' => $tokens),
  );
}

/**
 * Implements hook_tokens().
 */
function textimage_tokens($type, $tokens, array $data = array(), array $options = array()) {
  // Jumps out if not processing textimage tokens.
  if ($type != 'textimage') {
    return array();
  }
  // Jumps out with a warning if node is not available.
  if (!isset($data['node'])) {
    _textimage_diag(t('Textimage token(s) @tokens_list could not be resolved as no information about the context was available.', array('@tokens_list' => implode(', ', $tokens))), WATCHDOG_WARNING);
    return array();
  }
  // Process tokens.
  $replacements = \Drupal::service('textimage.factory')->processTokens('url', $tokens, $data['node']);
  $replacements += \Drupal::service('textimage.factory')->processTokens('uri', $tokens, $data['node']);
  return $replacements;
}

/**
 * Implements hook_metatag_token_types_alter().
 *
 * Integration of Textimage tokens with the Metatag module.
 */
function textimage_metatag_token_types_alter(&$options) {
  // Add Textimage tokens to the token types managed by Metatag,
  // for the node context.
  if ($options['context'] == 'node') {
    if (!isset($options['token types'])) {
      $options['token types'] = array();
    }
    if (!in_array('textimage', $options['token types'])) {
      $options['token types'][] = 'textimage';
    }
  }
}

// **** D8 specific ****
/*function textimage_entity_info(&$entity_info) {
  if (isset($entity_info['image_style'])) {
    $entity_info['image_style']['textimage'] = array('bingo' => 'bongo');
  }
}*/

/*function textimage_image_style_presave(\Drupal\Core\Entity\EntityInterface $entity) {

  //dpm($entity);
  $entity->set('textimage', 'BingoBongo');
//  dpm($entity);

}*/

//function textimage_textimage_style_load($entities) {

//  dpm($entity_type);
//  $entity->set('textimage', 'BingoBongo');
//  dpm($entities);
/*  foreach ($entities as $entity) {
    dpm($entity->name . ' . ' . $entity->isTextimage());
  }*/

//}

/* test hook for derivative creation */
/*function textimage_image_style_create_derivative($style, $original_uri, $derivative_uri) {
  ....TextimageFactory::setState();
  watchdog(
    'image',
    t(
      'Creating derivative image: %derivative for style: %style from image: %original',
      array(
        '%style' => $style->id(),
        '%derivative' => $derivative_uri,
        '%original' => $original_uri,
      )
    )
  );
}*/

// **** END D8 specific ****

/**
 * Implements hook_form_FORM_ID_alter().
 *
 * @see _textimage_image_style_form_form_alter()
 */
function textimage_form_image_style_form_alter(&$form, &$form_state, $form_id) {
/*$style = $form_state['controller']->getEntity();
dpm($style);
$effects = $style->getEffects();
foreach ($effects->sort() as $effect) {
dpm($effect);
};*/

/*  if (...::isTextimage($form_state['image_style'])) {*/
    $form['textimage_options'] = array(
      '#type' => 'details',
      '#tree' => TRUE,
      '#weight' => 10,
      '#title' => t('Textimage options'),
      '#description' => t('Define Textimage options specific for this image style.'),
    );
    // Define file storage wrapper used for the style images.
    $scheme_options = array();
    foreach (file_get_stream_wrappers(STREAM_WRAPPERS_WRITE_VISIBLE) as $scheme => $stream_wrapper) {
      $scheme_options[$scheme] = $stream_wrapper['name'];
    }
    $form['textimage_options']['uri_scheme'] = array(
      '#type' => 'radios',
      '#options' => $scheme_options,
      '#title' => t('Image destination'),
      '#description' => t('Select where Textimage image files should be stored. Private file storage has significantly more overhead than public files, but allows access restriction.'),
//  @todo     '#default_value' => $form_state['image_style']['textimage']['uri_scheme'],
      '#default_value' => 'public',
    );
    // Adds a submit handler to deal with textimage options.
//    $form['#submit'][] = '_textimage_image_style_form_textimage_submit';
  /*}*/
}

/**
 * Submit handler to deal with a style's Textimage options.
 *
 * @see _textimage_image_style_form_form_alter()
 */
/*function _textimage_image_style_form_textimage_submit($form, &$form_state) {
  $style = ...:get($form_state['values']['name']);
  // Update Textimage-specific style options.
  if ($style) {
    $style['textimage']['uri_scheme'] = $form_state['values']['textimage_options']['uri_scheme'];
    image_style_save($style);
  }
}*/

/**
 * Textimage functions.
 */

/**
 * Prepares variables to get a Textimage.
 *
 * Default template: textimage-formatter.html.twig.
 */
function template_preprocess_textimage_formatter(&$variables) {

  $output = array();

  // Get URI to image file.
  if ($variables['textimage'] && $variables['textimage'] instanceof Textimage) {
    $image_uri = $variables['textimage']->getUri();
  }
  else {
    $textimage = \Drupal::service('textimage.factory')->getTextimage();

    if ($variables['style_name']) {
      $textimage->styleByName($variables['style_name']);
    }
    else  {
      $textimage->effects($variables['effects']);
    }

    if ($variables['source_image_file']) {
      $textimage->sourceImageFile($variables['source_image_file']);
    }
    if ($variables['node']) {
      $textimage->node($variables['node']);
    }

    if ($variables['target_uri']) {
      $textimage->setTargetUri($variables['target_uri']);
    }
    else {
      $textimage->setCaching($variables['caching']);
    }

    if ($variables['force_hashed_filename']) {
      $textimage->setHashedFilename(TRUE);
    }

    $textimage->extension($variables['extension']);
    $textimage->process($variables['text']);
    $image_uri = $textimage->getUri();
  }

  // Render through image theme.
  if ($image_uri) {
    $image = \Drupal::service('image.factory')->get($image_uri);
    // Get the <img>.
    $output = array(
      '#theme' => 'image__textimage',
      '#uri' => $image_uri,
      '#width' => $image->getWidth(),
      '#height' => $image->getHeight(),
      '#alt' => \Drupal::service('textimage.factory')->processTextString($variables['alt'], NULL, $variables['node'], $variables['source_image_file']),
      '#title' => \Drupal::service('textimage.factory')->processTextString($variables['title'], NULL, $variables['node'], $variables['source_image_file']),
      '#attributes' => $variables['attributes'],
    );
    $image_url = file_create_url($image_uri);

    // Wrap the <img> in a container if requested.
    if (!empty($variables['image_container_attributes'])) {
      $container_attributes = array();
      foreach ($variables['image_container_attributes'] as $key => $value) {
        $container_attributes[$key] = str_replace('#textimage_derivative_url#', $image_url, $value);
      }
      $output = array(
        '#theme' => 'container',
        '#attributes' => $container_attributes,
        '#children' => $output,
      );
    }

    // Use the output to build a link if href specified.
    if ($variables['href']) {
      $output = array(
        '#type' => 'link',
        '#title' => $output,
        '#href' => ($variables['href'] == '#textimage_derivative_url#') ? $image_url : $variables['href'],
        '#options' => array(
          'html' => TRUE,
        ),
      );
    }
  }

  $variables['textimage_output'] = $output;
}

/**
 * Prepares variables to get a color info.
 *
 * Default template: textimage-color-detail.html.twig.
 */
function template_preprocess_textimage_color_detail(&$variables) {
  $attached['#attached']['library'][] = 'textimage/admin.ui';
  drupal_render($attached);   // @todo is this the final way?
  if ($variables['color']) {
    if ($variables['border']) {
      if ($variables['border_color'] == 'matchLuma') {
        $variables['border_color'] = ColorUtility::matchLuma($variables['color']);
      }
      else {
        $variables['border_color'] = Unicode::substr($variables['border_color'], 0, 7);
      }
    }
    $variables['color_opacity'] = ColorUtility::rgbaToOpacity($variables['color']);
    $variables['color'] = Unicode::substr($variables['color'], 0, 7);
  }
}

/**
 * Display/log a diagnostic message.
 *
 * @param string $message
 *   message
 * @param int $severity
 *   severity as per watchdog()
 * @param string $caller
 *   the calling function
 */
function _textimage_diag($message, $severity, $caller = NULL, $user_messages = TRUE) {
  if ($caller) {
    $message = t("@message - Function: @caller", array('@message' => $message, '@caller' => $caller));
  }
  if ($severity <= WATCHDOG_NOTICE) {
    \Drupal::logger('textimage')->log($severity, $message);
  }
  if ($severity <= \Drupal::config('textimage.settings')->get('message_level') && $user_messages) {
    switch ($severity) {
      case WATCHDOG_DEBUG:
      case WATCHDOG_INFO:
      case WATCHDOG_NOTICE:
        $type = 'status';
        break;

      case WATCHDOG_WARNING:
        $type = 'warning';
        break;

      default:
        $type = 'error';
    }
    drupal_set_message($message, $type, FALSE);
  }
}

/**
 * Helper - check if a module is enabled and at a specified release level.
 *
 * @param string $module
 *   Module name.
 * @param string $version
 *   (optional) Module version.
 * @param string $comparison_operator
 *   (optional) A comparison operator to test against $version.
 *
 * @return bool
 *   TRUE if module is enabled, FALSE otherwise.
 */
function _textimage_module_exists($module, $version = NULL, $comparison_operator = '>=') {
  if (!module_exists($module)) {
    return FALSE;
  }
  if ($version) {
    $module_info = system_get_info('module', $module);
    if (empty($module_info['version'])) {
      return TRUE;
    }
    return version_compare($module_info['version'], $version, $comparison_operator);
  }
  return TRUE;
}
