<?php

/**
 * @file
 * Textimage - Provides text to image manipulations.
 */

use Drupal\Component\Utility\Unicode;
use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\Core\StreamWrapper\StreamWrapperInterface;
use Drupal\Core\Template\Attribute;
use Drupal\image\ImageStyleInterface;
use Drupal\textimage\Component\ColorUtility;
use Drupal\textimage\Textimage;

/**
 * Implements hook_help().
 */
function textimage_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    case 'textimage.settings':
      $output = '<p>';
      $output .= t('Textimage provides image effects to generate images with overlaid text. ');
      $output .= t('Use <a href="@image">Image styles</a> features to create Image styles. ', array('@image' => \Drupal::url('image.style_list')));
      $output .= t('Adding Textimage effects to a style will identify it as relevant for Textimage. ');
      $output .= t('On the edit image style form, a "Textimage options" section allows selecting Textimage-specific options for the style.');
      $output .= '</p>';
      return $output;

  }
}

/**
 * Implements hook_theme().
 */
function textimage_theme() {
  $theme = array(
    // Format a textimage.
    'textimage_formatter' => array(
      'variables' => array(
        'textimage' => NULL,
        'style_name' => '',
        'effects' => array(),
        'text'   => array(),
        'extension' => 'png',
        'caching' => TRUE,
        'node' => NULL,
        'source_image_file' => NULL,
        'target_uri' => NULL,
        'force_hashed_filename' => FALSE,
        'alt'    => '',
        'title'  => '',
        'attributes' => array(),
        'image_container_attributes' => array(),
        'href' => '',
      ),
    ),
    // Textimage background image effect - summary.
    'textimage_background_summary' => array(
      'variables' => array('data' => NULL),
    ),
    // Textimage text image effect - summary.
    'textimage_text_summary' => array(
      'variables' => array('data' => NULL),
    ),
    // Render a preview of the Textimage in the image effect UI.
    'textimage_preview' => array(
      'variables' => array(
        'textimage_data' => [],
      ),
    ),
    // Render a color information box and string.
    'textimage_color_detail' => array(
      'variables' => array(
        'color' => '#000000',
        'border' => FALSE,
        'border_color' => '#000000',
      ),
    ),
  );
  return $theme;
}

/**
 * Implements hook_file_download().
 *
 * Control the access to files underneath the textimage directories.
 */
function textimage_file_download($uri) {
  $path = file_uri_target($uri);
  // Private file access for image style derivatives.
  if (strpos($path, 'textimage') === 0) {
    // Check that the file exists and is an image.
    $image = \Drupal::service('image.factory')->get($uri);
    if ($image->isValid()) {
      return array(
        // Send headers describing the image's size, and MIME-type...
        'Content-Type' => $image->getMimeType(),
        'Content-Length' => $image->getFileSize(),
        // By not explicitly setting them here, this uses normal Drupal
        // Expires, Cache-Control and ETag headers to prevent proxy or
        // browser caching of private images.
      );
    }
    return -1;
  }
  return NULL;
}

/**
 * Implements hook_cache_flush().
 */
function textimage_cache_flush() {
  return array('textimage');
}

/**
 * Implements hook_cron().
 */
function textimage_cron() {
  $uncached_dir = \Drupal::service('textimage.factory')->getStorePath('uncached');
  // Remove temporary, uncached, image files.
  if (file_exists($uncached_dir)) {
    if (file_unmanaged_delete_recursive($uncached_dir)) {
      \Drupal::service('textimage.logger')->notice(t("Textimage temporary image files removed."));
    }
    else {
      \Drupal::service('textimage.logger')->error(t("Textimage could not remove temporary image files."));
    }
  }
}

/**
 * Implements hook_token_info().
 */
function textimage_token_info() {
  $type = array(
    'name' => t('Textimage'),
    'description' => t('Tokens related to Textimage'),
    'needs-data' => 'node',
  );
  $tokens = array(
    'uri' => array(
      'name' => t("URI"),
      'description' => t("The URI(s) of a Textimage generated for a node's field. Use like <strong>[textimage:uri:field{:display}{:sequence}]</strong>, where:<br/><strong>field</strong> is the machine name of the field for which the Textimage is generated (e.g. body or field_xxxx);<br/><strong>display</strong> is an optional indication of the display view mode (e.g. default, full, teaser, etc.); 'default' is used if not specified; <br/><strong>sequence</strong> is an optional indication of the URI to return if Textimage produces more images for the same field (like e.g. in a multi-value Image field); if not specified, a comma-delimited string of all the URIs generated will be returned."),
      'dynamic' => TRUE,
    ),
    'url' => array(
      'name' => t("URL"),
      'description' => t("The URL(s) of a Textimage generated for a node's field. Use like <strong>[textimage:url:field{:display}{:sequence}]</strong>, where:<br/><strong>field</strong> is the machine name of the field for which the Textimage is generated (e.g. body or field_xxxx);<br/><strong>display</strong> is an optional indication of the display view mode (e.g. default, full, teaser, etc.); 'default' is used if not specified; <br/><strong>sequence</strong> is an optional indication of the URL to return if Textimage produces more images for the same field (like e.g. in a multi-value Image field); if not specified, a comma-delimited string of all the URLs generated will be returned."),
      'dynamic' => TRUE,
    ),
  );
  return array(
    'types'  => array('textimage' => $type),
    'tokens' => array('textimage' => $tokens),
  );
}

/**
 * Implements hook_tokens().
 */
function textimage_tokens($type, $tokens, array $data = array(), array $options = array()) {
  // Jumps out if not processing textimage tokens.
  if ($type != 'textimage') {
    return array();
  }
  // Jumps out with a warning if node is not available.
  if (!isset($data['node'])) {
    \Drupal::service('textimage.logger')->warning(t('Textimage token(s) @tokens_list could not be resolved as no information about the context was available.', array('@tokens_list' => implode(', ', $tokens))));
    return array();
  }
  // Process tokens.
  $replacements = \Drupal::service('textimage.factory')->processTokens('url', $tokens, $data['node']);
  $replacements += \Drupal::service('textimage.factory')->processTokens('uri', $tokens, $data['node']);
  return $replacements;
}

// @todo reintroduce hook_metatag_token_types_alter() once module is available.

/**
 * Implements hook_image_style_flush().
 */
function textimage_image_style_flush($style) {
  // Manage the textimage part of image style flushing.
  $factory = \Drupal::service('textimage.factory');
  if ($factory->isTextimage($style)) {
    $factory->flushStyle($style);
  }
}

/**
 * Implements hook_image_style_presave().
 *
 * Identify and store whether the image style is relevant for Textimage.
 */
function textimage_image_style_presave(ImageStyleInterface $style) {
  $factory = \Drupal::service('textimage.factory');
  $original_relevant = $factory->isTextimage($style);
  // Check if there are textimage effects.
  $relevant = FALSE;
  foreach ($style->getEffects() as $effect) {
    $definition = $effect->getPluginDefinition();
    if ($definition['provider'] == 'textimage') {
      $relevant = TRUE;
      break;
    }
  }
  // Flush Textimage if original was relevant but no longer.
  if (!$relevant && $original_relevant) {
    $factory->flushStyle($style);
  }
  // Store the setting.
  $style->setThirdPartySetting('textimage', 'is_relevant', $relevant);
}

/**
 * Implements hook_image_style_predelete().
 */
function textimage_image_style_predelete(ImageStyleInterface $style) {
  // Manage the textimage part of image style deletion.
  $factory = \Drupal::service('textimage.factory');
  if ($factory->isTextimage($style)) {
    $factory->flushStyle($style);
  }
}

/**
 * Make alterations to the core 'image_style_form' form.
 *
 * A fieldset is added if the image style is Textimage relevant.
 */
function textimage_form_image_style_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  $image_style = $form_state->getFormObject()->getEntity();
  if (\Drupal::service('textimage.factory')->isTextimage($image_style)) {
    $form['textimage_options'] = array(
      '#type' => 'details',
      '#weight' => 10,
      '#tree' => TRUE,
      '#open' => FALSE,
      '#title' => t('Textimage options'),
      '#description' => t('Define Textimage options specific for this image style.'),
    );
    // Define file storage wrapper used for the style images.
    $scheme_options = \Drupal::service('stream_wrapper_manager')->getNames(StreamWrapperInterface::WRITE_VISIBLE);
    $form['textimage_options']['uri_scheme'] = array(
      '#type' => 'radios',
      '#options' => $scheme_options,
      '#title' => t('Image destination'),
      '#description' => t('Select where Textimage image files should be stored. Private file storage has significantly more overhead than public files, but allows access restriction.'),
      '#default_value' => $image_style->getThirdPartySetting('textimage', 'uri_scheme', 'public'),
    );
    // Adds a validate handler to deal with textimage options.
    $form['#validate'][] = '_textimage_form_image_style_form_validate';
  }
}

/**
 * Submit handler to deal with the altered 'image_style_form' form.
 */
function _textimage_form_image_style_form_validate($form, FormStateInterface $form_state) {
  $image_style = $form_state->getFormObject()->getEntity();
  $image_style->setThirdPartySetting('textimage', 'uri_scheme', $form_state->getValue(['textimage_options', 'uri_scheme']));
}

/**
 * Prepares variables to get a Textimage.
 *
 * Default template: textimage-formatter.html.twig.
 */
function template_preprocess_textimage_formatter(&$variables) {
  // Get URI to image file.
  if ($variables['textimage'] && $variables['textimage'] instanceof Textimage) {
    $image_uri = $variables['textimage']->getUri();
  }
  else {
    $textimage = \Drupal::service('textimage.factory')->getTextimage();

    if ($variables['style_name']) {
      $textimage->styleByName($variables['style_name']);
    }
    else  {
      $textimage->effects($variables['effects']);
    }

    if ($variables['source_image_file']) {
      $textimage->sourceImageFile($variables['source_image_file']);
    }
    if ($variables['node']) {
      $textimage->node($variables['node']);
    }

    if ($variables['target_uri']) {
      $textimage->setTargetUri($variables['target_uri']);
    }
    else {
      $textimage->setCaching($variables['caching']);
    }

    if ($variables['force_hashed_filename']) {
      $textimage->setHashedFilename(TRUE);
    }

    $textimage->extension($variables['extension']);
    $textimage->process($variables['text']);
    $image_uri = $textimage->getUri();
  }

  // Render through image theme.
  if ($image_uri) {
    $image = \Drupal::service('image.factory')->get($image_uri);
    $title = \Drupal::service('textimage.factory')->processTextString($variables['title'], NULL, $variables['node'], $variables['source_image_file']);
    $alt = \Drupal::service('textimage.factory')->processTextString($variables['alt'], NULL, $variables['node'], $variables['source_image_file']);
    $url = file_create_url($image_uri);

    // Build anchor link data if needed.
    if ($variables['href']) {
      $path = ($variables['href']['path'] == '#textimage_derivative_url#') ? $url : $variables['href']['path'];
      $options = $variables['href']['options'];
      $href = \Drupal::service('url_generator')->generateFromPath($path, $options);
      $variables['anchor_attributes'] = new Attribute([
        'title' => $title,
        'href' => $href,
      ]);
    }
    // Replace occurrences of #textimage_derivative_url# with the actual URL
    // in the image container attributes.
    if (!empty($variables['image_container_attributes'])) {
      foreach ($variables['image_container_attributes'] as &$attribute) {
        foreach ($attribute as $key => $value) {
          $attribute[$key] = str_replace('#textimage_derivative_url#', $url, $value);
        }
      }
      $variables['image_container_attributes'] = new Attribute($variables['image_container_attributes']);
    }
    // Get the <img>.
    $variables['image'] = array(
      '#theme' => 'image__textimage',
      '#uri' => $image_uri,
      '#width' => $image->getWidth(),
      '#height' => $image->getHeight(),
      '#attributes' => $variables['attributes'],
    );
    if (!empty($title)) {
      $variables['image']['#title'] = $title;
    }
    if (!empty($alt)) {
      $variables['image']['#alt'] = $alt;
    }
  }
}

/**
 * Prepares variables to get a color info.
 *
 * Default template: textimage-color-detail.html.twig.
 */
function template_preprocess_textimage_color_detail(&$variables) {
  $variables['#attached']['library'][] = 'textimage/admin.ui';
  if ($variables['color']) {
    if ($variables['border']) {
      if ($variables['border_color'] == 'matchLuma') {
        $variables['border_color'] = ColorUtility::matchLuma($variables['color']);
      }
      else {
        $variables['border_color'] = Unicode::substr($variables['border_color'], 0, 7);
      }
    }
    $variables['color_opacity'] = ColorUtility::rgbaToOpacity($variables['color']);
    $variables['color'] = Unicode::substr($variables['color'], 0, 7);
  }
}

/**
 * Prepares variables to get a Textimage preview.
 *
 * Default template: textimage-preview.html.twig.
 */
function template_preprocess_textimage_preview(&$variables) {
  $variables['textimage_data']['layout']['x_pos'] = 'center';
  $variables['textimage_data']['layout']['y_pos'] = 'center';
  $variables['textimage_data']['layout']['x_offset'] = 0;
  $variables['textimage_data']['layout']['y_offset'] = 0;
  $variables['textimage_data']['layout']['overflow_action'] = 'extend';
  $variables['textimage_data']['debug_visuals'] = $variables['textimage_data']['preview_bar']['debug_visuals'];
  $variables['textimage_preview'] = array(
    '#theme' => 'textimage_formatter',
    '#text' => array($variables['textimage_data']['text_string']),
    '#effects' => array(
      array(
        'id' => 'textimage_text',
        'data' => $variables['textimage_data'],
      ),
    ),
    '#title' => t('Preview'),
    '#alt' => t('Display preview not available.'),
    '#caching' => FALSE,
  );
}
