# Schema for the Textimage module.

# Schema for settings.
textimage.settings:
  type: config_object
  label: 'Textimage settings'
  mapping:
    debug:
      type: boolean
      label: 'Display debugging information'
    default_extension:
      type: string
      label: 'Default image file extension'
    url_generation:
      type: mapping
      label: 'URL based generation'
      mapping:
        enabled:
          type: boolean
          label: 'Status of URL based generation'
        text_separator:
          type: string
          label: 'Sequence of characters to be used to split the URL text string'
    default_font:
      type: mapping
      label: 'Default font'
      mapping:
        name:
          type: string
          label: 'Default font name'
        uri:
          type: string
          label: 'Default font file URI'

# Schema for Textimage third party settings for image styles.
image.style.*.third_party.textimage:
  type: mapping
  label: 'Textimage settings for image styles'
  mapping:
    uri_scheme:
      type: string
      label: 'Textimage derivative scheme destination'


# Schema for Textimage provided image effects.
image.effect.textimage_background:
  type: mapping
  label: 'Textimage background effect'
  mapping:
    background_image:
      type: mapping
      mapping:
        mode:
          type: string
          label: 'Background image mode'
        uri:
          type: string
          label: 'Image file URI'
        fid:
          type: integer
          label: 'Image file FID'
    format:
      type: mapping
      mapping:
        extension:
          type: string
          label: 'Output image file extension'
        gif_transparent_color:
          type: color_hex
          label: 'Color to be used for transparency in GIF images'
    background:
      type: mapping
      mapping:
        color:
          type: color_hex
          label: 'Color'
        repeat:
          type: boolean
          label: 'Flag to reuse the color in following effects'
    exact:
      type: mapping
      mapping:
        width:
          type: integer
          label: 'Exact width in px'
        height:
          type: integer
          label: 'Exact height in px'
        position:
          type: string
          label: 'Position of the image on the resulting canvas'
        dimensions:
          type: string
          label: 'Action to take when the background image selected is bigger size than the canvas'
        crop:
          type: string
          label: 'Part of the selected background image that should be cropped'
    relative:
      type: mapping
      mapping:
        leftdiff:
          type: integer
          label: 'Left ribbon in px'
        rightdiff:
          type: integer
          label: 'Right ribbon in px'
        topdiff:
          type: integer
          label: 'Top ribbon in px'
        bottomdiff:
          type: integer
          label: 'Bottom ribbon in px'


# Schema for Textimage provided field formatter settings.
field.formatter.settings.textimage_text_field_formatter:
  type: mapping
  label: 'Textimage text field formatter settings'
  mapping:
    image_link:
      type: string
      label: 'Link image to'
    image_text_values:
      type: string
      label: 'Multi-value text field'
    image_style:
      type: string
      label: 'Image style'
    image_alt:
      type: text
      label: 'Image alternate text'
    image_title:
      type: text
      label: 'Image title'
    image_build_deferred:
      type: boolean
      label: 'Defer building of textimage to subsequent request'
field.formatter.settings.textimage_image_field_formatter:
  type: mapping
  label: 'Textimage image field formatter settings'
  mapping:
    image_link:
      type: string
      label: 'Link image to'
    image_style:
      type: string
      label: 'Image style'
    image_alt:
      type: text
      label: 'Image alternate text'
    image_title:
      type: text
      label: 'Image title'
